name: event_manager_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Local storage and utilities
  sqflite: ^2.3.2
  path: ^1.9.0
  flutter_dotenv: ^5.1.0
  provider: ^6.1.1
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2

  # Firebase core and feature SDKs (scaffold only; do not initialize yet)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
